
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package cup.example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int RBRACK = 19;
  public static final int TIMES = 6;
  public static final int LT = 11;
  public static final int ELSE = 22;
  public static final int PLUS = 3;
  public static final int INT = 24;
  public static final int RBRACE = 21;
  public static final int RPAREN = 8;
  public static final int WHILE = 27;
  public static final int SEMI = 2;
  public static final int LBRACK = 18;
  public static final int RETURN = 25;
  public static final int IF = 23;
  public static final int LBRACE = 20;
  public static final int LPAREN = 7;
  public static final int GT = 13;
  public static final int ID = 29;
  public static final int LE = 10;
  public static final int COMMA = 17;
  public static final int NUMBER = 28;
  public static final int EOF = 0;
  public static final int DIVIDE = 9;
  public static final int GE = 12;
  public static final int MINUS = 4;
  public static final int error = 1;
  public static final int ASSIGN = 16;
  public static final int EQ = 14;
  public static final int VOID = 26;
  public static final int NEQ = 15;
  public static final int UMINUS = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "PLUS",
  "MINUS",
  "UMINUS",
  "TIMES",
  "LPAREN",
  "RPAREN",
  "DIVIDE",
  "LE",
  "LT",
  "GE",
  "GT",
  "EQ",
  "NEQ",
  "ASSIGN",
  "COMMA",
  "LBRACK",
  "RBRACK",
  "LBRACE",
  "RBRACE",
  "ELSE",
  "IF",
  "INT",
  "RETURN",
  "VOID",
  "WHILE",
  "NUMBER",
  "ID"
  };
}

